scratchpad_space = 11
launch_timeout = 5

[[scratchpad]]
name = "kitty"
target_type = "title"
target = "Scratchpad"
position = [1000, 50]
size = [900, 1150]
launch_type = "app_with_arg"
launch_command = ["kitty.app", "--title", "Scratchpad"]
