line-length = 90
fix=true

[lint]
ignore = ["D401"]
select = ["B", "D", "E", "F", "I", "N", "Q", "W"]

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 90

[lint.flake8-quotes]
inline-quotes = "double"

[lint.pydocstyle]
convention = "numpy"
