[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
command = "kitty --class scratchpad --session ~/.config/kitty/tmux_session.conf"
class = "scratchpad"
size = "60% 90%"
position = "40% 5%"
animation = "fromTop"
